### PR TITLE
optionally get GitHub PAT from environment var

### PR DESCRIPTION
**Pull request by plicease**
This doesn't completely address #3, and there are probably some security concerns to work out, but this might help.

### CODE REVIEW

**Comment by eserte** [comment]
I think having the personal access token in a query parameter is deprecated now and maybe even not possible. Instead, nowadays one should use an HTTP request header: `Authorization: token $GITHUB_TOKEN`.
This also has the advantage that the security concerns are gone (unless in diagnostic messages the whole http request headers would be dumped).

**Comment by plicease** [comment]
> I think having the personal access token in a query parameter is deprecated now and maybe even not possible. Instead, nowadays one should use an HTTP request header: `Authorization: token $GITHUB_TOKEN`.
> This also has the advantage that the security concerns are gone (unless in diagnostic messages the whole http request headers would be dumped).

I agree that an authorization header is the right way to go here, unfortunately AB doesn't support setting headers yet.  I did start working on this:

https://github.com/PerlAlien/Alien-Build/pull/141

but I think that PR was too ambitious.  I think adding headers to just one of the fetch plugins and forcing its usage if you need a header could be doable.

**Comment by plicease** [comment]
After some more consideration I think supporting headers on most or all of the core plugins should be doable, so I opened this:

https://github.com/PerlAlien/Alien-Build/issues/256

**Comment by plicease** [comment]
Closing this for security reasons.  Will implement as described in #13

**Pull request closed without merging**
